### ISSUE TITLE
[infrastructure] Add specification for UI and translation testing.

### ISSUE THREAD

**Issue by amed** [webmontag/webmontag-koeln.de-reloaded#14]
It should come after add localization.

**Comment by jhilden** [comment]
I personally think writing these tests should be part of writing the feature #13, and not a separate task.

it might be a separate task to build the necessary infrastructure (Capybara, etc.) for writing acceptance tests.  also #8 might be helpful for this

**Comment by amed** [comment]
It is invalid.
