### ISSUE TITLE
Go live with relaunched website

### ISSUE THREAD

**Issue by jhilden** [webmontag/webmontag-koeln.de-reloaded#26]
The page will be hosted from http://webmontag.netlify.com/ (the `master` branch of this repo is automatically deployed there.

After #22 and #23 are merged/closed we need to do the following:
* [x] set up DNS for webmontag-koeln.de with a `CNAME` record pointing to `webmontag.netlify.com` (and possibly also a record for `www`). See: https://www.netlify.com/docs/custom-domains/
* [x] remove the legacy app (heroku? github?)

**Comment by amed** [comment]
What do you meen by remove the legacy app heroku? github?

**Comment by jhilden** [comment]
> What do you meen by remove the legacy app heroku? github?

@koos mentioned that there is an old app that we can turn off after the new one is live.  I'm unsure about heroku.  Maybe he can shed some light on it.
