### ISSUE TITLE
[bug] Missed text in index page

### ISSUE THREAD

**Issue by amed** [webmontag/webmontag-koeln.de-reloaded#44]
The text is hidden as tags,

![image](https://cloud.githubusercontent.com/assets/5637272/20057953/a72ec188-a4ee-11e6-8784-681c36e19e80.png)

![image](https://cloud.githubusercontent.com/assets/5637272/20057985/c884528a-a4ee-11e6-87f1-2a24632754c8.png)

**Comment by jhilden** [comment]
can you point to the place in the code where I can see this?

**Comment by amed** [comment]
```
p
    a class="change-language" href="#" Switch to English version
h2 Alles begann in Köln …
p
    Web Montag ist ein informelles, nicht-kommerzielles, dezentral organisiertes Treffen, das
    zum Ziel hat, all diejenigen miteinander zu verbinden, die die Zukunft des Internet gestalten.
    Inspiriert von der Kultur Silicon Valleys startete der Web Montag gegen Ende 2005 in Köln als'
```

https://github.com/webmontag/webmontag-koeln.de-reloaded/blob/master/source/shared/index/_intro.slim#L27
